Repository yagpdb-cc/yagpdb-cc, pull requests merged in 2021-04, with the labels that each got.

#175 Create EmoteFilter.go.tmpl
  moderation/EmoteFilter.go.tmpl
Labels: enhancement

#180 Small Util Update
  util/ghostping-v1.go.tmpl
  util/ghostping-v2.go.tmpl
  util/json.go.tmpl
Labels: enhancement

#185 Addition of Nickname Moderation CC
  moderation/NicknameModeration.go.tmpl
Labels: changes requested, enhancement, good first issue, help wanted

#190 Midterm markdown refactor
  afk/README.md
  afk/afk.go.tmpl
  suggestion/README.md
  suggestion/suggestion.go.tmpl
Labels: documentation, enhancement

#191 add starboard v2
  fun/starboard v2/readme.md
  fun/starboard v2/starboard.go.tmpl
  fun/starboard v2/starboardListener.go.tmpl
Labels: changes requested, enhancement

#193 Yet Another Markdown Pull Request
  birthday/README.md
Labels: documentation
